Use the following code for the questions below:

In [45]:
import numpy as np


In [46]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])


1) How many negative numbers are there?

2) How many positive numbers are there?

3) How many even positive numbers are there?

4) If you were to add 3 to each data point, how many positive numbers would there be?

5) If you squared each number, what would the new mean and standard deviation be?

6) A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering.

7) Calculate the z-score for each data point. Recall that the z-score is given by:

                                        Z = x − μ / σ


8) Copy the setup and exercise directions from More Numpy Practice into your numpy_exercises.py and add your solutions.

In [47]:
# 1) How many negative numbers are there?

is_neg = a[(a < 0)]
is_neg

array([-2, -1, -6, -7])

In [48]:
# 2) How many positive numbers are there?

is_pos = a[(a > 0)]
is_pos

array([ 4, 10, 12, 23,  3])

In [49]:
# 3) How many even positive numbers are there?

is_pos = a[(a > 0)]
is_even = a[(a % 2 == 0)]



In [61]:
even_pos = (a > 0) & (a % 2 == 0)
even_pos

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False])

In [62]:
a[even_pos]

array([ 4, 10, 12])

In [52]:
# 4) If you were to add 3 to each data point, how many positive numbers would there be?



In [53]:
# 5) If you squared each number, what would the new mean and standard deviation be?

In [54]:
# 6) A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering.

In [55]:
# 7) Calculate the z-score for each data point. Recall that the z-score is given by: Z = x − μ / σ

In [56]:
# 8) Copy the setup and exercise directions from More Numpy Practice into your numpy_exercises.py and add your solutions.