Use the following code for the questions below:

In [245]:
import numpy as np


In [246]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])


1) How many negative numbers are there?

2) How many positive numbers are there?

3) How many even positive numbers are there?

4) If you were to add 3 to each data point, how many positive numbers would there be?

5) If you squared each number, what would the new mean and standard deviation be?

6) A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering.

7) Calculate the z-score for each data point. Recall that the z-score is given by:

                                        Z = x − μ / σ


8) Copy the setup and exercise directions from More Numpy Practice into your numpy_exercises.py and add your solutions.

In [247]:
# 1) How many negative numbers are there?

is_neg = a[(a < 0)]


In [248]:
len(is_neg)

4

In [249]:
# 2) How many positive numbers are there?

is_pos = a[(a > 0)]
is_pos

array([ 4, 10, 12, 23,  3])

In [250]:
len(is_pos)

5

In [251]:
# 3) How many even positive numbers are there?

is_pos = a[(a > 0)]
is_even = a[(a % 2 == 0)]



In [252]:
len(is_even)

8

In [253]:
even_pos = (a > 0) & (a % 2 == 0)
even_pos

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False])

In [254]:
len(even_pos)

12

In [255]:
a[even_pos]

array([ 4, 10, 12])

In [256]:
# 4) If you were to add 3 to each data point, how many positive numbers would there be?
a += 3


In [257]:
a

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3, -3,  6, -4])

In [258]:
# 5) If you squared each number, what would the new mean and standard deviation be?

a **= 2


In [259]:
a

array([ 49, 169, 225, 676,   1,   4,   9,   9,   9,   9,  36,  16])

In [260]:
np.mean(a)

# mean is 146

101.0

In [261]:
np.std(a)
# standard deviation is 231.54

186.64672512530188

In [271]:
# 6) A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set.

# subtracting the mean from each data point
a -= 146

center_a = a - a.mean()
center_a 

# see if I can write it as 
# a -= np.mean(a)

TypeError: unsupported operand type(s) for -=: 'list' and 'int'

In [272]:
center_a = a - a.mean()
center_a

AttributeError: 'list' object has no attribute 'mean'

In [263]:
# printing the array to check the result of the above^
a

array([ -97,   23,   79,  530, -145, -142, -137, -137, -137, -137, -110,
       -130])

In [264]:
# 7) Calculate the z-score for each data point. Recall that the z-score is given by: Z = x − μ / σ

In [277]:
z_scores = a / np.std(a)
    

In [278]:
z_scores

array([0.34815531, 0.69631062, 1.04446594, 1.39262125, 1.74077656,
       2.08893187, 2.43708718, 2.7852425 , 3.13339781, 3.48155312])

In [267]:
# 8) Copy the setup and exercise directions from More Numpy Practice into your numpy_exercises.py and add your solutions.


- - -

- - -

- - -

- - -

In [268]:
# Life w/o numpy to life with numpy

## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]



In [269]:

# Use python's built in functionality/operators to determine the following:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

sum_of_a = sum(a)

# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

min_of_a = min(a)

# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

max_of_a = max(a)

# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

mean_of_a = sum_of_a / len(a)

# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together
product_of_a = 1
for num in a:
    product_of_a *= num

# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

squares_of_a = [num ** 2 for num in a]

# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

odds_in_a = [num % 2 != 0 for num in a]

# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

evens_in_a = [num % 2 == 0 for num in a]

## What about life in two dimensions? A list of lists is a matrix, a table, a spreadsheet, a chessboard...

In [279]:
## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.
b = [
    [3, 4, 5],
    [6, 7, 8]
]

# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)

b = np.array([[3, 4, 5],[6, 7, 8]])

np.sum(b)



# Exercise 2 - refactor the following to use numpy. 
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  

np.min([b])



# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])



# Exercise 4 - refactor the following using numpy to find the mean of b
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

b.mean()


# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number

np.prod(b)


# Exercise 6 - refactor the following to use numpy to find the list of squares 
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)



# Exercise 7 - refactor using numpy to determine the odds_in_b 
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)

b[b % 2 != 0]


# Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)

b[b % 2 == 0]

# Exercise 9 - print out the shape of the array b.

np.shape(b)

# Exercise 10 - transpose the array b.

np.transpose(b)

# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

b.reshape(1,6)

# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

b.reshape(6,1)
or 
np.reshape(b, (6,1,))


array([[3, 6],
       [4, 7],
       [5, 8]])

In [280]:
## Setup 3
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

# HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.

c = np.array(c)

# Exercise 1 - Find the min, max, sum, and product of c.

np.min(c)
np.max(c)
np.sum(c)
np.product(c)



# Exercise 2 - Determine the standard deviation of c.

np.std(c)


# Exercise 3 - Determine the variance of c.

c.var(c)

# Exercise 4 - Print out the shape of the array c

np.shape(c)

# Exercise 5 - Transpose c and print out transposed result.

transpose_c = np.transpose(c)

# Exercise 6 - Get the dot product of the array c with c. 

np.product(c)



dot_product_of_c = np.dot(c, c)

# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261

cat = transpose_c * c
np.sum(cat)

# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.

np.product(cat)


In [281]:
## Setup 4
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

# Exercise 1 - Find the sine of all the numbers in d

np.sin(d)


# Exercise 2 - Find the cosine of all the numbers in d
np.cos(d)


# Exercise 3 - Find the tangent of all the numbers in d
np.tan(d)



# Exercise 4 - Find all the negative numbers in d

negd = d[d < 0]



# Exercise 5 - Find all the positive numbers in d

d[d > 0]

# Exercise 6 - Return an array of only the unique numbers in d.

np.unique(b)

# Exercise 7 - Determine how many unique numbers there are in d.

np.count_nonzero(np.unique(d)) + np.count_nonzero(np.unique(d == 0))

# or

len(np.unique(d))

# Exercise 8 - Print out the shape of d.

np.shape(d)

# Exercise 9 - Transpose and then print out the shape of d.

np.transpose(d)
np.shape(d)

# d.transpose().shape

# Exercise 10 - Reshape d into an array of 9 x 2

d.reshape(9, 2)


array([3, 4, 5, 6, 7, 8])